import { 
  Product, 
  InventoryItem, 
  Order, 
  ReturnOrder, 
  Settlement, 
  Vendor, 
  Warehouse,
  Alert,
  Task,
  KPIData,
  SalesData,
  Portal
} from '@/types';

// Helper to generate dates
const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

// Mock KPI Data
export const mockKPIData: KPIData = {
  totalSales: 2847500,
  ordersToday: 156,
  inventoryValue: 4523000,
  lowStockItems: 23,
  pendingReturns: 47,
  pendingSettlements: 12,
  salesGrowth: 12.5,
  ordersGrowth: 8.3,
};

// Mock Sales Data (last 30 days)
export const mockSalesData: SalesData[] = [
  { date: daysAgo(29), portal: 'amazon', orders: 45, revenue: 125000, returns: 3 },
  { date: daysAgo(29), portal: 'flipkart', orders: 38, revenue: 98000, returns: 2 },
  { date: daysAgo(29), portal: 'meesho', orders: 28, revenue: 45000, returns: 1 },
  { date: daysAgo(28), portal: 'amazon', orders: 52, revenue: 145000, returns: 4 },
  { date: daysAgo(28), portal: 'flipkart', orders: 41, revenue: 112000, returns: 3 },
  { date: daysAgo(28), portal: 'meesho', orders: 33, revenue: 52000, returns: 2 },
  { date: daysAgo(27), portal: 'amazon', orders: 48, revenue: 132000, returns: 2 },
  { date: daysAgo(27), portal: 'flipkart', orders: 44, revenue: 118000, returns: 4 },
  { date: daysAgo(27), portal: 'firstcry', orders: 15, revenue: 38000, returns: 1 },
  { date: daysAgo(26), portal: 'amazon', orders: 55, revenue: 158000, returns: 5 },
  { date: daysAgo(26), portal: 'flipkart', orders: 47, revenue: 125000, returns: 3 },
  { date: daysAgo(26), portal: 'blinkit', orders: 22, revenue: 28000, returns: 0 },
  { date: daysAgo(25), portal: 'amazon', orders: 61, revenue: 175000, returns: 4 },
  { date: daysAgo(25), portal: 'flipkart', orders: 52, revenue: 138000, returns: 4 },
  { date: daysAgo(25), portal: 'meesho', orders: 35, revenue: 58000, returns: 2 },
  { date: daysAgo(24), portal: 'amazon', orders: 58, revenue: 162000, returns: 3 },
  { date: daysAgo(24), portal: 'flipkart', orders: 49, revenue: 132000, returns: 2 },
  { date: daysAgo(24), portal: 'firstcry', orders: 18, revenue: 45000, returns: 1 },
  { date: daysAgo(23), portal: 'amazon', orders: 63, revenue: 182000, returns: 5 },
  { date: daysAgo(23), portal: 'flipkart', orders: 55, revenue: 148000, returns: 4 },
  { date: daysAgo(22), portal: 'amazon', orders: 67, revenue: 195000, returns: 4 },
  { date: daysAgo(22), portal: 'flipkart', orders: 58, revenue: 155000, returns: 3 },
  { date: daysAgo(21), portal: 'amazon', orders: 72, revenue: 210000, returns: 6 },
  { date: daysAgo(21), portal: 'flipkart', orders: 62, revenue: 168000, returns: 5 },
  { date: daysAgo(20), portal: 'amazon', orders: 68, revenue: 198000, returns: 4 },
  { date: daysAgo(20), portal: 'flipkart', orders: 59, revenue: 158000, returns: 3 },
  { date: daysAgo(19), portal: 'amazon', orders: 75, revenue: 218000, returns: 5 },
  { date: daysAgo(19), portal: 'flipkart', orders: 64, revenue: 172000, returns: 4 },
];

// Mock Products
export const mockProducts: Product[] = [
  {
    productId: 'PROD-001',
    name: 'Premium Wireless Earbuds Pro',
    category: 'Electronics',
    brand: 'TechAudio',
    description: 'High-quality wireless earbuds with noise cancellation',
    basePrice: 2999,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=200',
    createdAt: daysAgo(120),
    updatedAt: daysAgo(5),
  },
  {
    productId: 'PROD-002',
    name: 'Smart Fitness Watch X2',
    category: 'Electronics',
    brand: 'FitTech',
    description: 'Advanced fitness tracking with heart rate monitor',
    basePrice: 4999,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=200',
    createdAt: daysAgo(90),
    updatedAt: daysAgo(3),
  },
  {
    productId: 'PROD-003',
    name: 'Organic Cotton T-Shirt',
    category: 'Apparel',
    brand: 'EcoWear',
    description: '100% organic cotton casual t-shirt',
    basePrice: 599,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=200',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
  },
  {
    productId: 'PROD-004',
    name: 'Stainless Steel Water Bottle',
    category: 'Home & Kitchen',
    brand: 'HydroLife',
    description: 'Insulated water bottle keeps drinks cold for 24 hours',
    basePrice: 799,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=200',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    productId: 'PROD-005',
    name: 'Baby Care Gift Set',
    category: 'Baby Products',
    brand: 'TenderCare',
    description: 'Complete baby care essentials gift set',
    basePrice: 1299,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=200',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    productId: 'PROD-006',
    name: 'Portable Bluetooth Speaker',
    category: 'Electronics',
    brand: 'SoundWave',
    description: 'Waterproof portable speaker with 20-hour battery',
    basePrice: 1999,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=200',
    createdAt: daysAgo(75),
    updatedAt: daysAgo(4),
  },
  {
    productId: 'PROD-007',
    name: 'Yoga Mat Premium',
    category: 'Sports & Fitness',
    brand: 'FlexFit',
    description: 'Non-slip yoga mat with carrying strap',
    basePrice: 899,
    status: 'inactive',
    imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=200',
    createdAt: daysAgo(100),
    updatedAt: daysAgo(15),
  },
  {
    productId: 'PROD-008',
    name: 'LED Desk Lamp',
    category: 'Home & Kitchen',
    brand: 'BrightLife',
    description: 'Adjustable LED lamp with USB charging port',
    basePrice: 1499,
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=200',
    createdAt: daysAgo(55),
    updatedAt: daysAgo(2),
  },
];

// Mock Inventory
export const mockInventory: InventoryItem[] = [
  {
    skuId: 'SKU-AMZ-001',
    productId: 'PROD-001',
    productName: 'Premium Wireless Earbuds Pro',
    portal: 'amazon',
    availableStock: 245,
    reservedStock: 32,
    warehouse: 'Mumbai FC',
    agingDays: 45,
    lowStockThreshold: 50,
    lastUpdated: daysAgo(1),
  },
  {
    skuId: 'SKU-FLK-001',
    productId: 'PROD-001',
    productName: 'Premium Wireless Earbuds Pro',
    portal: 'flipkart',
    availableStock: 18,
    reservedStock: 5,
    warehouse: 'Delhi FC',
    agingDays: 38,
    lowStockThreshold: 50,
    lastUpdated: daysAgo(1),
  },
  {
    skuId: 'SKU-AMZ-002',
    productId: 'PROD-002',
    productName: 'Smart Fitness Watch X2',
    portal: 'amazon',
    availableStock: 156,
    reservedStock: 28,
    warehouse: 'Mumbai FC',
    agingDays: 32,
    lowStockThreshold: 30,
    lastUpdated: daysAgo(1),
  },
  {
    skuId: 'SKU-MSH-002',
    productId: 'PROD-002',
    productName: 'Smart Fitness Watch X2',
    portal: 'meesho',
    availableStock: 12,
    reservedStock: 3,
    warehouse: 'Bangalore FC',
    agingDays: 85,
    lowStockThreshold: 25,
    lastUpdated: daysAgo(2),
  },
  {
    skuId: 'SKU-AMZ-003',
    productId: 'PROD-003',
    productName: 'Organic Cotton T-Shirt',
    portal: 'amazon',
    availableStock: 520,
    reservedStock: 45,
    warehouse: 'Delhi FC',
    agingDays: 22,
    lowStockThreshold: 100,
    lastUpdated: daysAgo(1),
  },
  {
    skuId: 'SKU-FLK-003',
    productId: 'PROD-003',
    productName: 'Organic Cotton T-Shirt',
    portal: 'flipkart',
    availableStock: 380,
    reservedStock: 62,
    warehouse: 'Mumbai FC',
    agingDays: 28,
    lowStockThreshold: 100,
    lastUpdated: daysAgo(1),
  },
  {
    skuId: 'SKU-BLK-004',
    productId: 'PROD-004',
    productName: 'Stainless Steel Water Bottle',
    portal: 'blinkit',
    availableStock: 8,
    reservedStock: 2,
    warehouse: 'Mumbai FC',
    agingDays: 15,
    lowStockThreshold: 50,
    lastUpdated: daysAgo(1),
  },
  {
    skuId: 'SKU-FCY-005',
    productId: 'PROD-005',
    productName: 'Baby Care Gift Set',
    portal: 'firstcry',
    availableStock: 92,
    reservedStock: 18,
    warehouse: 'Bangalore FC',
    agingDays: 42,
    lowStockThreshold: 20,
    lastUpdated: daysAgo(1),
  },
  {
    skuId: 'SKU-AMZ-006',
    productId: 'PROD-006',
    productName: 'Portable Bluetooth Speaker',
    portal: 'amazon',
    availableStock: 5,
    reservedStock: 2,
    warehouse: 'Delhi FC',
    agingDays: 92,
    lowStockThreshold: 25,
    lastUpdated: daysAgo(3),
  },
  {
    skuId: 'SKU-MSH-007',
    productId: 'PROD-007',
    productName: 'Yoga Mat Premium',
    portal: 'meesho',
    availableStock: 210,
    reservedStock: 15,
    warehouse: 'Bangalore FC',
    agingDays: 68,
    lowStockThreshold: 50,
    lastUpdated: daysAgo(2),
  },
];

// Mock Orders
export const mockOrders: Order[] = [
  {
    orderId: 'ORD-2024-001',
    portal: 'amazon',
    portalOrderId: 'AMZ-402-7891234',
    customerId: 'CUST-001',
    customerName: 'Rahul Sharma',
    customerEmail: 'rahul.s@email.com',
    customerPhone: '+91 98765 43210',
    shippingAddress: '123 MG Road, Koramangala, Bangalore 560034',
    items: [
      { skuId: 'SKU-AMZ-001', productName: 'Premium Wireless Earbuds Pro', quantity: 1, price: 2999, status: 'shipped' },
    ],
    totalAmount: 2999,
    status: 'shipped',
    orderDate: daysAgo(2),
    trackingNumber: 'AWB123456789',
    statusTimeline: [
      { status: 'pending', timestamp: daysAgo(2) },
      { status: 'confirmed', timestamp: daysAgo(2), note: 'Order confirmed' },
      { status: 'packed', timestamp: daysAgo(1), note: 'Packed at Mumbai FC' },
      { status: 'shipped', timestamp: daysAgo(1), note: 'Shipped via BlueDart' },
    ],
  },
  {
    orderId: 'ORD-2024-002',
    portal: 'flipkart',
    portalOrderId: 'FLK-OD-789456123',
    customerId: 'CUST-002',
    customerName: 'Priya Patel',
    customerEmail: 'priya.p@email.com',
    customerPhone: '+91 87654 32109',
    shippingAddress: '45 Nehru Nagar, Andheri West, Mumbai 400053',
    items: [
      { skuId: 'SKU-FLK-003', productName: 'Organic Cotton T-Shirt', quantity: 2, price: 599, status: 'delivered' },
      { skuId: 'SKU-FLK-001', productName: 'Premium Wireless Earbuds Pro', quantity: 1, price: 2999, status: 'delivered' },
    ],
    totalAmount: 4197,
    status: 'delivered',
    orderDate: daysAgo(5),
    deliveryDate: daysAgo(1),
    trackingNumber: 'FKT987654321',
    statusTimeline: [
      { status: 'pending', timestamp: daysAgo(5) },
      { status: 'confirmed', timestamp: daysAgo(5) },
      { status: 'packed', timestamp: daysAgo(4) },
      { status: 'shipped', timestamp: daysAgo(3) },
      { status: 'delivered', timestamp: daysAgo(1), note: 'Delivered to customer' },
    ],
  },
  {
    orderId: 'ORD-2024-003',
    portal: 'meesho',
    portalOrderId: 'MSH-ORD-456789',
    customerId: 'CUST-003',
    customerName: 'Amit Kumar',
    customerEmail: 'amit.k@email.com',
    customerPhone: '+91 76543 21098',
    shippingAddress: '78 Rajaji Nagar, Chennai 600028',
    items: [
      { skuId: 'SKU-MSH-002', productName: 'Smart Fitness Watch X2', quantity: 1, price: 4999, status: 'packed' },
    ],
    totalAmount: 4999,
    status: 'packed',
    orderDate: daysAgo(1),
    trackingNumber: 'MSH456789123',
    statusTimeline: [
      { status: 'pending', timestamp: daysAgo(1) },
      { status: 'confirmed', timestamp: daysAgo(1) },
      { status: 'packed', timestamp: daysAgo(0), note: 'Ready for dispatch' },
    ],
  },
  {
    orderId: 'ORD-2024-004',
    portal: 'firstcry',
    portalOrderId: 'FCY-123789456',
    customerId: 'CUST-004',
    customerName: 'Sneha Reddy',
    customerEmail: 'sneha.r@email.com',
    customerPhone: '+91 65432 10987',
    shippingAddress: '23 Jubilee Hills, Hyderabad 500033',
    items: [
      { skuId: 'SKU-FCY-005', productName: 'Baby Care Gift Set', quantity: 2, price: 1299, status: 'pending' },
    ],
    totalAmount: 2598,
    status: 'pending',
    orderDate: daysAgo(0),
    statusTimeline: [
      { status: 'pending', timestamp: daysAgo(0), note: 'Awaiting confirmation' },
    ],
  },
  {
    orderId: 'ORD-2024-005',
    portal: 'blinkit',
    portalOrderId: 'BLK-QCK-789123',
    customerId: 'CUST-005',
    customerName: 'Vikram Singh',
    customerEmail: 'vikram.s@email.com',
    customerPhone: '+91 54321 09876',
    shippingAddress: '56 Sector 18, Noida 201301',
    items: [
      { skuId: 'SKU-BLK-004', productName: 'Stainless Steel Water Bottle', quantity: 3, price: 799, status: 'delivered' },
    ],
    totalAmount: 2397,
    status: 'delivered',
    orderDate: daysAgo(1),
    deliveryDate: daysAgo(1),
    statusTimeline: [
      { status: 'pending', timestamp: daysAgo(1) },
      { status: 'confirmed', timestamp: daysAgo(1) },
      { status: 'packed', timestamp: daysAgo(1) },
      { status: 'shipped', timestamp: daysAgo(1) },
      { status: 'delivered', timestamp: daysAgo(1), note: 'Quick commerce delivery' },
    ],
  },
  {
    orderId: 'ORD-2024-006',
    portal: 'amazon',
    portalOrderId: 'AMZ-402-5678901',
    customerId: 'CUST-006',
    customerName: 'Kavita Menon',
    customerEmail: 'kavita.m@email.com',
    customerPhone: '+91 43210 98765',
    shippingAddress: '89 Marine Drive, Kochi 682001',
    items: [
      { skuId: 'SKU-AMZ-006', productName: 'Portable Bluetooth Speaker', quantity: 1, price: 1999, status: 'confirmed' },
      { skuId: 'SKU-AMZ-003', productName: 'Organic Cotton T-Shirt', quantity: 1, price: 599, status: 'confirmed' },
    ],
    totalAmount: 2598,
    status: 'confirmed',
    orderDate: daysAgo(0),
    statusTimeline: [
      { status: 'pending', timestamp: daysAgo(0) },
      { status: 'confirmed', timestamp: daysAgo(0), note: 'Payment verified' },
    ],
  },
];

// Mock Returns
export const mockReturns: ReturnOrder[] = [
  {
    returnId: 'RET-2024-001',
    orderId: 'ORD-2024-002',
    portal: 'flipkart',
    reason: 'size_issue',
    status: 'pending',
    claimEligible: true,
    requestDate: daysAgo(2),
    refundAmount: 599,
    items: [
      { skuId: 'SKU-FLK-003', productName: 'Organic Cotton T-Shirt', quantity: 1, price: 599, status: 'returned' },
    ],
  },
  {
    returnId: 'RET-2024-002',
    orderId: 'ORD-2024-005',
    portal: 'blinkit',
    reason: 'damaged',
    status: 'approved',
    claimEligible: true,
    requestDate: daysAgo(1),
    refundAmount: 799,
    items: [
      { skuId: 'SKU-BLK-004', productName: 'Stainless Steel Water Bottle', quantity: 1, price: 799, status: 'returned' },
    ],
  },
  {
    returnId: 'RET-2024-003',
    orderId: 'ORD-2024-001',
    portal: 'amazon',
    reason: 'not_as_described',
    status: 'eligible',
    claimEligible: true,
    requestDate: daysAgo(3),
    refundAmount: 2999,
    items: [
      { skuId: 'SKU-AMZ-001', productName: 'Premium Wireless Earbuds Pro', quantity: 1, price: 2999, status: 'returned' },
    ],
  },
];

// Mock Settlements
export const mockSettlements: Settlement[] = [
  {
    settlementId: 'SET-AMZ-2024-01',
    portal: 'amazon',
    amount: 485000,
    commission: 72750,
    fees: 14550,
    netAmount: 397700,
    status: 'completed',
    cycleStart: daysAgo(14),
    cycleEnd: daysAgo(7),
    expectedDate: daysAgo(5),
    actualDate: daysAgo(5),
    ordersCount: 156,
  },
  {
    settlementId: 'SET-FLK-2024-01',
    portal: 'flipkart',
    amount: 328000,
    commission: 49200,
    fees: 9840,
    netAmount: 268960,
    status: 'completed',
    cycleStart: daysAgo(14),
    cycleEnd: daysAgo(7),
    expectedDate: daysAgo(4),
    actualDate: daysAgo(3),
    ordersCount: 112,
  },
  {
    settlementId: 'SET-MSH-2024-01',
    portal: 'meesho',
    amount: 156000,
    commission: 23400,
    fees: 4680,
    netAmount: 127920,
    status: 'pending',
    cycleStart: daysAgo(7),
    cycleEnd: daysAgo(0),
    expectedDate: daysAgo(-2),
    ordersCount: 78,
  },
  {
    settlementId: 'SET-AMZ-2024-02',
    portal: 'amazon',
    amount: 512000,
    commission: 76800,
    fees: 15360,
    netAmount: 419840,
    status: 'pending',
    cycleStart: daysAgo(7),
    cycleEnd: daysAgo(0),
    expectedDate: daysAgo(-3),
    ordersCount: 168,
  },
  {
    settlementId: 'SET-FCY-2024-01',
    portal: 'firstcry',
    amount: 89000,
    commission: 13350,
    fees: 2670,
    netAmount: 72980,
    status: 'delayed',
    cycleStart: daysAgo(21),
    cycleEnd: daysAgo(14),
    expectedDate: daysAgo(7),
    ordersCount: 45,
  },
];

// Mock Vendors
export const mockVendors: Vendor[] = [
  {
    vendorId: 'VEN-001',
    name: 'TechGadgets India Pvt Ltd',
    email: 'contact@techgadgets.in',
    phone: '+91 22 4567 8901',
    address: '123 Electronic City, Bangalore 560100',
    warehouses: ['Mumbai FC', 'Delhi FC'],
    status: 'active',
    joinDate: daysAgo(365),
    totalProducts: 45,
    totalOrders: 2840,
  },
  {
    vendorId: 'VEN-002',
    name: 'FashionHub Exports',
    email: 'sales@fashionhub.com',
    phone: '+91 11 2345 6789',
    address: '456 Textile Market, Mumbai 400001',
    warehouses: ['Mumbai FC', 'Bangalore FC'],
    status: 'active',
    joinDate: daysAgo(280),
    totalProducts: 128,
    totalOrders: 5620,
  },
  {
    vendorId: 'VEN-003',
    name: 'BabyCare Essentials',
    email: 'support@babycare.in',
    phone: '+91 80 9876 5432',
    address: '789 Kids Market, Delhi 110001',
    warehouses: ['Delhi FC', 'Bangalore FC'],
    status: 'active',
    joinDate: daysAgo(180),
    totalProducts: 56,
    totalOrders: 1890,
  },
];

// Mock Warehouses
export const mockWarehouses: Warehouse[] = [
  {
    warehouseId: 'WH-MUM-01',
    name: 'Mumbai FC',
    location: 'Bhiwandi, Maharashtra',
    capacity: 50000,
    utilized: 38500,
    vendorId: 'VEN-001',
    storageCostPerDay: 0.5,
  },
  {
    warehouseId: 'WH-DEL-01',
    name: 'Delhi FC',
    location: 'Manesar, Haryana',
    capacity: 45000,
    utilized: 32000,
    vendorId: 'VEN-001',
    storageCostPerDay: 0.45,
  },
  {
    warehouseId: 'WH-BLR-01',
    name: 'Bangalore FC',
    location: 'Hosur Road, Karnataka',
    capacity: 35000,
    utilized: 28500,
    vendorId: 'VEN-002',
    storageCostPerDay: 0.55,
  },
];

// Mock Alerts
export const mockAlerts: Alert[] = [
  {
    alertId: 'ALT-001',
    type: 'low_inventory',
    severity: 'critical',
    title: 'Critical Low Stock',
    message: 'Portable Bluetooth Speaker has only 5 units left on Amazon',
    portal: 'amazon',
    entityId: 'SKU-AMZ-006',
    timestamp: daysAgo(0),
    read: false,
    actionUrl: '/inventory',
  },
  {
    alertId: 'ALT-002',
    type: 'payment_delay',
    severity: 'warning',
    title: 'Settlement Delayed',
    message: 'FirstCry settlement SET-FCY-2024-01 is overdue by 7 days',
    portal: 'firstcry',
    entityId: 'SET-FCY-2024-01',
    timestamp: daysAgo(0),
    read: false,
    actionUrl: '/settlements',
  },
  {
    alertId: 'ALT-003',
    type: 'low_inventory',
    severity: 'warning',
    title: 'Low Stock Warning',
    message: 'Water Bottle stock below threshold on Blinkit',
    portal: 'blinkit',
    entityId: 'SKU-BLK-004',
    timestamp: daysAgo(1),
    read: false,
    actionUrl: '/inventory',
  },
  {
    alertId: 'ALT-004',
    type: 'claim_eligible',
    severity: 'info',
    title: 'Claim Eligible',
    message: 'Return RET-2024-003 is eligible for claim filing',
    portal: 'amazon',
    entityId: 'RET-2024-003',
    timestamp: daysAgo(1),
    read: true,
    actionUrl: '/returns',
  },
  {
    alertId: 'ALT-005',
    type: 'return_initiated',
    severity: 'info',
    title: 'New Return Request',
    message: 'Customer initiated return for order ORD-2024-002',
    portal: 'flipkart',
    entityId: 'RET-2024-001',
    timestamp: daysAgo(2),
    read: true,
    actionUrl: '/returns',
  },
];

// Mock Tasks
export const mockTasks: Task[] = [
  {
    taskId: 'TASK-001',
    title: 'Restock Low Inventory Items',
    description: 'Review and restock all items below threshold',
    assignedTo: 'ops-001',
    status: 'in_progress',
    priority: 'high',
    dueDate: daysAgo(-1),
    createdAt: daysAgo(2),
    portal: 'amazon',
  },
  {
    taskId: 'TASK-002',
    title: 'Follow up on FirstCry Settlement',
    description: 'Contact FirstCry regarding delayed payment',
    assignedTo: 'admin-001',
    status: 'pending',
    priority: 'urgent',
    dueDate: daysAgo(0),
    createdAt: daysAgo(1),
    portal: 'firstcry',
  },
  {
    taskId: 'TASK-003',
    title: 'Process Pending Returns',
    description: 'Review and approve pending return requests',
    assignedTo: 'ops-001',
    status: 'pending',
    priority: 'medium',
    dueDate: daysAgo(-2),
    createdAt: daysAgo(3),
  },
  {
    taskId: 'TASK-004',
    title: 'Update Product Catalog',
    description: 'Add new summer collection products',
    assignedTo: 'vendor-001',
    status: 'completed',
    priority: 'low',
    dueDate: daysAgo(1),
    createdAt: daysAgo(7),
  },
];

// Portal configurations
export const portalConfigs = [
  { id: 'amazon' as Portal, name: 'Amazon', color: 'hsl(33, 100%, 50%)', icon: '🛒' },
  { id: 'flipkart' as Portal, name: 'Flipkart', color: 'hsl(45, 100%, 51%)', icon: '🛍️' },
  { id: 'meesho' as Portal, name: 'Meesho', color: 'hsl(340, 82%, 52%)', icon: '📦' },
  { id: 'firstcry' as Portal, name: 'FirstCry', color: 'hsl(199, 89%, 48%)', icon: '👶' },
  { id: 'blinkit' as Portal, name: 'Blinkit', color: 'hsl(45, 100%, 51%)', icon: '⚡' },
];
